### ISSUE TITLE
C++ Syntax Highlighting not working

### ISSUE THREAD

**Issue by rtunazzz** [patstockwell/vim-monokai-tasty#33]
Hi!

Beginner (neo)Vim user here... Love your theme!! Works lovely for Python, JS & TS from my testing. I am having some issues with getting syntax highlighting to work properly with C++ files though (on MacOS). See the screenshots below:

### Theme turned OFF
(`colorscheme vim-monokai-tasty` commented out in my config file) - Notice how variable declarations such as `int` or `bool` are highlighted just fine
<img width="1787" alt="Screen Shot 2021-05-21 at 1 41 37 PM" src="https://user-images.githubusercontent.com/38296319/119132257-c8859800-ba3a-11eb-92da-bf7412d28a66.png">
### Theme turned ON
Notice how variable declarations such as `int` or `bool` are just white, without any highlights
<img width="1787" alt="Screen Shot 2021-05-21 at 1 44 21 PM" src="https://user-images.githubusercontent.com/38296319/119132262-c9b6c500-ba3a-11eb-9452-c272c90594db.png">

## Steps to reproduce
As I mentioned I am pretty new to Vim (and Vim plugins) so I am not sure what would be useful for you to trace the issue. Let me know if it'd be helpful if I shared my config files or anything like that.

**Comment by rtunazzz** [comment]
I went ahead and inspected the output of the `:highlight` command in Vim and I noticed that a few C/ C++ highlight definitions are cleared - for example `Type`, `cppSTLfuntion`, `cCustomDot`, `cCustomPtr` and a bunch of others.

Would be awesome if you could add those to the theme! 🤩

#### Screenshot from `:highlight`:

<img  src="https://user-images.githubusercontent.com/38296319/119135073-3d0e0600-ba3e-11eb-83ae-a694d0ee160f.png">

**Comment by patstockwell** [comment]
Done! 🎉 

Thanks for raising an issue with some nice clear screen shot comparisons.
To help me identify missing syntax groups I have a vim alias called `:What`. I have this in my _.vimrc_:

```vim
" `What` will print out the syntax group that the cursor is currently above.
" from https://www.reddit.com/r/vim/comments/6z4aau/how_to_stop_vim_from_autohighlighting_italics_in/
command! What echomsg synIDattr(synID(line('.'), col('.'), 1), 'name')
```

I opened a C++ file and placed my cursor over a `int` keyword and I got the highlight group `cType`. **I've added a highlight for cType in vim-monokai-tasty**. I used italic light blue to be consistent with the approach Sublime Text's implementation.

See these commits: e6816633a42ad652174af64944b7f42ba750e41f abb8e4f50ba2e7273a8cd1eb2e45427b0222f463 

**Before**
![image](https://user-images.githubusercontent.com/14284552/119752021-97e0ab00-bedf-11eb-99d5-4913089bc700.png)


**After**
![Screen Shot 2021-05-27 at 11 30 47 am](https://user-images.githubusercontent.com/14284552/119751858-47694d80-bedf-11eb-8848-b06bc5f8ff0c.png)

**Sublime (for comparison)**
![Screen Shot 2021-05-27 at 11 31 04 am](https://user-images.githubusercontent.com/14284552/119751828-3ddfe580-bedf-11eb-9aef-65c96cbf126b.png)

Some of the other words in the file without any highlights simply return nothing when running `:What`. This tells me that vim hasn't identified that particular syntax with a highlight group, so we simply can't give them a colour.

If you are interested in getting even better colours, there might be C++ plugins out there that define `match` regex's to identify more accurate syntax groups. These plugins will have their own syntax group names that would allow you to apply even more highlights.

Thanks again for taking the time to make a git issue 🏅

**Comment by rtunazzz** [comment]
Hi! Thanks for taking the time to look into this & fixing it.

Love that you mentioned the `What` alias, very useful!

Some types are still missing (`cppModifier`, `cppType` - both are linked to `Type` which is cleared) but that's no big deal. I will try to figure it out myself and perpahs open a pull request at some point.

Either way, thank you for the awesome theme and thanks for the update! ⭐️
